# Site settings
title: Noga Raviv
email: nospam+at+gmail.com
description: >
  Hi, I'm Noga!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nogaraviv.com" # the base hostname & protocol for your site
tag_colors:
  design: E74C3C
  development: 3498DB
  video: 2ECC71
  
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
collections:
  projects:
    output: true
    permalink: /:title/
